name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and Push API
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/lucidata-api:latest
          ghcr.io/${{ github.repository }}/lucidata-api:${{ github.sha }}
    
    - name: Build and Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/lucidata-frontend:latest
          ghcr.io/${{ github.repository }}/lucidata-frontend:${{ github.sha }}
    
    - name: Build and Push LLM Engine
      uses: docker/build-push-action@v4
      with:
        context: ./llm_engine
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/lucidata-llm:latest
          ghcr.io/${{ github.repository }}/lucidata-llm:${{ github.sha }}
    
    - name: Build and Push Query Runner
      uses: docker/build-push-action@v4
      with:
        context: ./query_runner
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/lucidata-query-runner:latest
          ghcr.io/${{ github.repository }}/lucidata-query-runner:${{ github.sha }}
    
    - name: Build and Push Response Formatter
      uses: docker/build-push-action@v4
      with:
        context: ./response_formatter
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/lucidata-response-formatter:latest
          ghcr.io/${{ github.repository }}/lucidata-response-formatter:${{ github.sha }}
    
    # For a real deployment, you'd add steps here to update your infrastructure
    # For example, updating a Kubernetes deployment or triggering a cloud deployment
